import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "turn_booking_language";

export const LANGUAGES = {
  ar: { code: "ar", label: "العربية", dir: "rtl" },
  he: { code: "he", label: "עברית", dir: "rtl" },
};

const dictionary = {
  ar: {
    language: "اللغة",
    arabic: "العربية",
    hebrew: "עברית",
    accessibility: "إمكانيات الوصول",
    openAccessibility: "فتح إمكانيات الوصول",
    close: "إغلاق",
    reset: "إعادة ضبط",
    privacyPolicy: "سياسة الخصوصية",
    sitePolicy: "سياسة الموقع",
    fontSize: "حجم الخط",
    increaseFont: "تكبير الخط",
    decreaseFont: "تصغير الخط",
    readableFont: "خط أوضح",
    highContrast: "تباين عال",
    grayscale: "درجات رمادية",
    underlineLinks: "تسطير الروابط",
    reduceMotion: "تقليل الحركة",
    policies: "السياسات",
    loginTitle: "تسجيل الدخول",
    loginSubtitle: "أدخل بياناتك للوصول إلى لوحة التحكم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور",
    login: "دخول",
    demoAccounts: "حسابات تجريبية",
    fillOnClick: "اضغط للتعبئة",
    welcome: "مرحبًا",
    adminRole: "المدير العام",
    ownerRole: "صاحب صالون",
    staffRole: "موظفة",
    platformTitle: "منصة إدارة حجوزات احترافية لكل الأعمال",
    platformSubtitle: "نظام SaaS متعدد المستأجرين لإدارة الصالونات والعيادات والمراكز، حجوزات وموظفون وخدمات واشتراكات في مكان واحد.",
    dataIsolation: "عزل كامل لبيانات كل محل",
    smartBooking: "حجز ذكي يمنع التعارض تلقائيًا",
    publicPage: "صفحة حجز عامة لكل محل",
    privacyTitle: "سياسة الخصوصية",
    privacyIntro: "نحترم خصوصية المستخدمين وأصحاب المحلات، ونستخدم البيانات فقط لتشغيل نظام الحجز وإدارة المواعيد والخدمات.",
    privacyDataTitle: "البيانات التي نجمعها",
    privacyData: "قد تشمل البيانات الاسم، رقم الهاتف، البريد الإلكتروني، تفاصيل الحجز، بيانات المحل، الموظفين والخدمات، وسجلات النشاط اللازمة للحماية والدعم.",
    privacyUseTitle: "طريقة استخدام البيانات",
    privacyUse: "تُستخدم البيانات لإتمام الحجوزات، إرسال الإشعارات، إدارة الاشتراكات، تحسين الخدمة، ومساعدة صاحب المحل عند طلب الدعم.",
    privacySecurityTitle: "حماية المعلومات",
    privacySecurity: "يتم تقييد الوصول حسب الصلاحيات، وتُطبّق ضوابط حماية على الخادم، ولا يتم عرض بيانات المحلات لغير أصحاب الصلاحية.",
    termsTitle: "سياسة الموقع",
    termsIntro: "استخدام النظام يعني الالتزام بسياسة الموقع واحترام بيانات العملاء والمواعيد والخدمات المسجلة.",
    termsUseTitle: "الاستخدام المسموح",
    termsUse: "يُستخدم الموقع لإدارة الحجوزات والخدمات والموظفين فقط، ويُمنع استخدامه لإرسال محتوى مضلل أو غير قانوني.",
    termsOwnerTitle: "مسؤولية صاحب المحل",
    termsOwner: "صاحب المحل مسؤول عن صحة الخدمات والأسعار وساعات العمل وسياسة قبول أو رفض الحجوزات المعروضة للعملاء.",
    termsAvailabilityTitle: "توفر الخدمة",
    termsAvailability: "قد تتوقف الخدمة مؤقتًا للصيانة أو التحديثات، وسنعمل على تقليل أي انقطاع قدر الإمكان.",
    backHome: "العودة للرئيسية",
    builtBy: "تم بناء هذا الموقع في شركة",
    navDashboard: "لوحة التحكم",
    navBusinesses: "إدارة المحلات",
    navManagers: "إدارة المدراء",
    navAppointments: "الحجوزات",
    navRejectedAppointments: "الحجوزات التي تم رفضها",
    navServices: "الخدمات",
    navEmployees: "الموظفون",
    navWorkingHours: "ساعات العمل",
    navSubscription: "الاشتراك",
    navActivity: "سجل النشاط",
    navSettings: "إعدادات المحل",
    navStaffAppointments: "مواعيدي",
    roleSuperAdmin: "المدير العام",
    roleBusinessOwner: "صاحب المحل",
    roleStaff: "موظف",
    mainMenu: "القائمة الرئيسية",
    businessPlatform: "نظام الحجوزات",
    adminBrandSub: "تجربة رقمية أذكى",
    businessBrandSub: "منصة إدارة المواعيد",
    storeLogo: "شعار المحل",
    logout: "تسجيل الخروج",
    openSidebar: "فتح القائمة الجانبية",
    closeSidebar: "إغلاق القائمة الجانبية",
    notifications: "الإشعارات",
    markRead: "تعيين كمقروءة",
    deleteAll: "حذف الكل",
    noNotifications: "لا توجد إشعارات",
    managingBusiness: "إدارة",
    businessFallback: "المحل",
    welcomeUser: "أهلًا،",
    remoteControlHelp: "تحكم عن بعد لمساعدة صاحب المحل",
    todayActivitySummary: "نظرة سريعة على نشاط محلّك اليوم",
    publicBookingLink: "رابط الحجز العام لمحلّك",
    shareBookingLink: "شاركه مع زبائنك ليحجزوا مباشرة",
    copy: "نسخ",
    open: "فتح",
    todayBookings: "حجوزات اليوم",
    weekBookings: "حجوزات الأسبوع",
    upcomingAppointments: "المواعيد القادمة",
    allBookings: "كل الحجوزات",
    customer: "الزبون",
    service: "الخدمة",
    employee: "الموظف",
    appointmentTime: "الموعد",
    status: "الحالة",
    action: "إجراء",
    accept: "قبول",
    reject: "رفض",
    acceptedAppointment: "تم قبول الدور",
    rejectedAppointment: "تم رفض الدور",
    noUpcomingAppointments: "لا توجد مواعيد قادمة",
    newBookingsAppearHere: "ستظهر الحجوزات الجديدة هنا",
    statusPending: "بانتظار التأكيد",
    statusConfirmed: "مؤكد",
    statusCompleted: "مكتمل",
    statusCancelled: "ملغي",
    statusNoShow: "لم يحضر",
    adminDashboardTitle: "لوحة التحكم العامة",
    adminDashboardSub: "نظرة شاملة على كل المحلات المشتركة في المنصة",
    addNewBusiness: "إضافة محل جديد",
    totalBusinesses: "إجمالي المحلات",
    activeBusinesses: "محلات مفعلة",
    totalAppointments: "إجمالي الحجوزات",
    businessOwners: "أصحاب المحلات",
    latestBusinesses: "أحدث المحلات",
    viewAll: "عرض الكل",
    business: "المحل",
    link: "الرابط",
    active: "مفعل",
    inactive: "موقوف",
    noBusinessesYet: "لا توجد محلات بعد",
    addFirstBusinessHint: "ابدأ بإضافة أول محل من صفحة إدارة المحلات",
    managersManagementTitle: "إدارة المدراء",
    managersManagementSub: "إضافة المدراء وتعديل بيانات الدخول والتواصل",
    newManager: "مدير جديد",
    addManager: "إضافة مدير",
    editManager: "تعديل مدير",
    managerName: "اسم المدير",
    addedDate: "تاريخ الإضافة",
    actions: "إجراءات",
    managerUpdated: "تم تحديث بيانات المدير",
    managerAdded: "تمت إضافة المدير",
    noManagers: "لا يوجد مدراء",
    addFirstManagerHint: "أضف أول مدير للنظام",
    leavePasswordBlank: "اتركها فارغة إذا لا تريد تغييرها",
    save: "حفظ",
    cancel: "إلغاء",
    edit: "تعديل",
    phone: "الهاتف",
    businessesManagementTitle: "إدارة المحلات",
    businessesManagementSub: "إنشاء وإدارة المحلات وأصحابها واشتراكاتهم",
    subscriptionsEndingSoon: "اشتراكات تنتهي خلال 7 أيام",
    endsToday: "ينتهي اليوم",
    daysLeft: "باقي",
    days: "أيام",
    noExpiringSubscriptions: "لا توجد اشتراكات قاربت على الانتهاء",
    newBusiness: "محل جديد",
    searchBusinessPlaceholder: "ابحث باسم المحل...",
    search: "بحث",
    owner: "صاحب المحل",
    statistics: "الإحصائيات",
    subscription: "الاشتراك",
    subscriptionStart: "بداية الاشتراك",
    subscriptionEnd: "نهاية الاشتراك",
    adminSubscriptionSub: "عرض تفاصيل اشتراك المحل المحدد",
    businessSubscriptionSub: "تفاصيل اشتراك محلك في المنصة",
    currentPlan: "الباقة الحالية",
    monthlyPlan: "الباقة الشهرية",
    yearlyPlan: "الباقة السنوية",
    monthUnit: "شهر",
    yearUnit: "سنة",
    expired: "منتهٍ",
    remainingDays: "أيام متبقية",
    subscriptionContactHint: "لتجديد الاشتراك أو ترقية الباقة، يرجى التواصل مع إدارة المنصة.",
    noActiveSubscription: "لا يوجد اشتراك فعال",
    activateSubscriptionHint: "تواصل مع إدارة المنصة لتفعيل اشتراك المحل.",
    control: "تحكم",
    renewSubscription: "تجديد الاشتراك",
    activate: "تفعيل",
    deactivate: "إيقاف",
    monthly: "شهري",
    yearly: "سنوي",
    appointmentsShort: "حجز",
    employeesShort: "موظف",
    servicesShort: "خدمة",
    noBusinesses: "لا توجد محلات",
    addFirstBusinessForStart: "أضف أول محل للبدء",
    bookingStepService: "الخدمة",
    bookingStepEmployee: "الموظف",
    bookingStepDateTime: "اليوم والوقت",
    bookingStepDetails: "بياناتك",
    bookingPageUnavailable: "تعذر فتح صفحة الحجز",
    bookEasily: "احجز موعدك بسهولة",
    chooseService: "اختر الخدمة",
    chooseEmployee: "اختر الموظف",
    chooseDateTime: "اختر اليوم والوقت",
    enterYourDetails: "أدخل بياناتك",
    freeService: "الخدمة مجانية",
    noServicesAvailable: "لا توجد خدمات متاحة",
    anyAvailableEmployee: "أي موظف متاح",
    autoChooseEmployee: "سنختار أول موظف متاح في الوقت المناسب",
    date: "التاريخ",
    closedTodayTitle: "المحل مغلق اليوم نستميحكم عذرًا",
    nextOpenPrefix: "يسرنا استقبالكم",
    nearestWorkingDay: "في أقرب يوم عمل قادم",
    allSlotsBooked: "كل الأدوار المتاحة محجوزة",
    tryAnotherDayOrEmployee: "جرّب يومًا آخر أو اختر موظفًا مختلفًا",
    continue: "متابعة",
    fullName: "الاسم الكامل",
    phoneNumber: "رقم الهاتف",
    optionalEmail: "البريد الإلكتروني (اختياري)",
    freeServicePaymentHint: "الخدمة مجانية ولا تحتاج إلى دفع",
    bookingUnavailableNoPayment: "عذرًا، الحجز غير متاح حاليًا لعدم تفعيل أي طريقة دفع لدى المحل.",
    paymentMethod: "طريقة الدفع",
    onlinePayment: "دفع إلكتروني",
    payAtStore: "دفع في المحل",
    payOnlineHint: "ادفع الآن عبر البوابة",
    payAtStoreHint: "ادفع عند حضورك",
    confirmFreeBooking: "تأكيد الحجز المجاني",
    continueToPayment: "المتابعة للدفع",
    poweredByBooking: "مدعوم بمنصة إدارة الحجوزات",
    bookingRejectedTitle: "تم رفض الدور",
    bookingPendingTitle: "طلبك بانتظار التأكيد",
    bookingConfirmedTitle: "تم تأكيد حجزك",
    bookingRejectedText: "نعتذر، تم رفض هذا الدور. يمكنك اختيار موعد آخر.",
    bookingPendingText: "سنظهر لك هنا إذا تم قبول الدور أو رفضه.",
    bookingConfirmedText: "نتطلع لرؤيتك. هذه تفاصيل موعدك:",
    bookAnother: "حجز موعد آخر",
    back: "رجوع",
    sunday: "الأحد",
    monday: "الإثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    saturday: "السبت",
  },
  he: {
    language: "שפה",
    arabic: "العربية",
    hebrew: "עברית",
    accessibility: "נגישות",
    openAccessibility: "פתיחת נגישות",
    close: "סגירה",
    reset: "איפוס",
    privacyPolicy: "מדיניות פרטיות",
    sitePolicy: "מדיניות האתר",
    fontSize: "גודל טקסט",
    increaseFont: "הגדלת טקסט",
    decreaseFont: "הקטנת טקסט",
    readableFont: "גופן קריא",
    highContrast: "ניגודיות גבוהה",
    grayscale: "גווני אפור",
    underlineLinks: "קו תחתון לקישורים",
    reduceMotion: "הפחתת תנועה",
    policies: "מדיניות",
    loginTitle: "כניסה למערכת",
    loginSubtitle: "הזן את הפרטים כדי להיכנס ללוח הבקרה",
    email: "אימייל",
    password: "סיסמה",
    showPassword: "הצגת סיסמה",
    hidePassword: "הסתרת סיסמה",
    login: "כניסה",
    demoAccounts: "חשבונות לדוגמה",
    fillOnClick: "לחץ למילוי",
    welcome: "ברוך הבא",
    adminRole: "מנהל ראשי",
    ownerRole: "בעל סלון",
    staffRole: "עובדת",
    platformTitle: "מערכת מקצועית לניהול תורים לכל עסק",
    platformSubtitle: "מערכת SaaS לניהול סלונים, מרפאות ומרכזים: תורים, עובדים, שירותים ומנויים במקום אחד.",
    dataIsolation: "הפרדה מלאה של נתוני כל עסק",
    smartBooking: "תורים חכמים שמונעים התנגשויות",
    publicPage: "עמוד הזמנות ציבורי לכל עסק",
    privacyTitle: "מדיניות פרטיות",
    privacyIntro: "אנו מכבדים את פרטיות המשתמשים ובעלי העסקים ומשתמשים במידע רק להפעלת מערכת התורים וניהול השירותים.",
    privacyDataTitle: "המידע שאנו אוספים",
    privacyData: "המידע עשוי לכלול שם, טלפון, אימייל, פרטי תור, פרטי עסק, עובדים, שירותים ויומני פעילות לצורכי אבטחה ותמיכה.",
    privacyUseTitle: "כיצד משתמשים במידע",
    privacyUse: "המידע משמש לביצוע תורים, שליחת התראות, ניהול מנויים, שיפור השירות וסיוע לבעל העסק בעת בקשת תמיכה.",
    privacySecurityTitle: "אבטחת מידע",
    privacySecurity: "הגישה מוגבלת לפי הרשאות, קיימות הגנות בצד השרת, ונתוני עסקים אינם מוצגים למי שאינו מורשה.",
    termsTitle: "מדיניות האתר",
    termsIntro: "השימוש במערכת מחייב שמירה על מדיניות האתר וכיבוד נתוני הלקוחות, התורים והשירותים.",
    termsUseTitle: "שימוש מותר",
    termsUse: "האתר מיועד לניהול תורים, שירותים ועובדים בלבד, ואסור להשתמש בו לתוכן מטעה או בלתי חוקי.",
    termsOwnerTitle: "אחריות בעל העסק",
    termsOwner: "בעל העסק אחראי לנכונות השירותים, המחירים, שעות הפעילות ומדיניות אישור או דחיית התורים המוצגת ללקוחות.",
    termsAvailabilityTitle: "זמינות השירות",
    termsAvailability: "השירות עשוי להיעצר זמנית לצורך תחזוקה או עדכונים, ואנו נפעל לצמצם כל הפרעה ככל האפשר.",
    backHome: "חזרה לדף הראשי",
    builtBy: "האתר נבנה בחברת",
    navDashboard: "לוח בקרה",
    navBusinesses: "ניהול עסקים",
    navManagers: "ניהול מנהלים",
    navAppointments: "תורים",
    navRejectedAppointments: "תורים שנדחו",
    navServices: "שירותים",
    navEmployees: "עובדים",
    navWorkingHours: "שעות פעילות",
    navSubscription: "מנוי",
    navActivity: "יומן פעילות",
    navSettings: "הגדרות העסק",
    navStaffAppointments: "התורים שלי",
    roleSuperAdmin: "מנהל ראשי",
    roleBusinessOwner: "בעל העסק",
    roleStaff: "עובד",
    mainMenu: "תפריט ראשי",
    businessPlatform: "מערכת תורים",
    adminBrandSub: "חוויה דיגיטלית חכמה",
    businessBrandSub: "מערכת ניהול תורים",
    storeLogo: "לוגו העסק",
    logout: "יציאה",
    openSidebar: "פתיחת תפריט צד",
    closeSidebar: "סגירת תפריט צד",
    notifications: "התראות",
    markRead: "סימון כנקרא",
    deleteAll: "מחיקת הכל",
    noNotifications: "אין התראות",
    managingBusiness: "ניהול",
    businessFallback: "העסק",
    welcomeUser: "שלום,",
    remoteControlHelp: "שליטה מרחוק כדי לסייע לבעל העסק",
    todayActivitySummary: "מבט מהיר על פעילות העסק היום",
    publicBookingLink: "קישור ההזמנות הציבורי של העסק",
    shareBookingLink: "שתפו אותו עם הלקוחות כדי שיוכלו להזמין ישירות",
    copy: "העתקה",
    open: "פתיחה",
    todayBookings: "תורי היום",
    weekBookings: "תורי השבוע",
    upcomingAppointments: "התורים הקרובים",
    allBookings: "כל התורים",
    customer: "לקוח",
    service: "שירות",
    employee: "עובד",
    appointmentTime: "מועד",
    status: "סטטוס",
    action: "פעולה",
    accept: "אישור",
    reject: "דחייה",
    acceptedAppointment: "התור אושר",
    rejectedAppointment: "התור נדחה",
    noUpcomingAppointments: "אין תורים קרובים",
    newBookingsAppearHere: "תורים חדשים יופיעו כאן",
    statusPending: "ממתין לאישור",
    statusConfirmed: "מאושר",
    statusCompleted: "הושלם",
    statusCancelled: "בוטל",
    statusNoShow: "לא הגיע",
    adminDashboardTitle: "לוח הבקרה הראשי",
    adminDashboardSub: "מבט כולל על כל העסקים המחוברים למערכת",
    addNewBusiness: "הוספת עסק חדש",
    totalBusinesses: "סה״כ עסקים",
    activeBusinesses: "עסקים פעילים",
    totalAppointments: "סה״כ תורים",
    businessOwners: "בעלי עסקים",
    latestBusinesses: "עסקים אחרונים",
    viewAll: "הצגת הכל",
    business: "עסק",
    link: "קישור",
    active: "פעיל",
    inactive: "מושבת",
    noBusinessesYet: "אין עסקים עדיין",
    addFirstBusinessHint: "התחילו בהוספת העסק הראשון מעמוד ניהול העסקים",
    managersManagementTitle: "ניהול מנהלים",
    managersManagementSub: "הוספה ועריכה של פרטי כניסה ותקשורת למנהלים",
    newManager: "מנהל חדש",
    addManager: "הוספת מנהל",
    editManager: "עריכת מנהל",
    managerName: "שם המנהל",
    addedDate: "תאריך הוספה",
    actions: "פעולות",
    managerUpdated: "פרטי המנהל עודכנו",
    managerAdded: "המנהל נוסף",
    noManagers: "אין מנהלים",
    addFirstManagerHint: "הוסיפו את המנהל הראשון למערכת",
    leavePasswordBlank: "השאירו ריק אם אין צורך לשנות",
    save: "שמירה",
    cancel: "ביטול",
    edit: "עריכה",
    phone: "טלפון",
    businessesManagementTitle: "ניהול עסקים",
    businessesManagementSub: "יצירה וניהול של עסקים, בעלים ומנויים",
    subscriptionsEndingSoon: "מנויים שמסתיימים בתוך 7 ימים",
    endsToday: "מסתיים היום",
    daysLeft: "נותרו",
    days: "ימים",
    noExpiringSubscriptions: "אין מנויים שמתקרבים לסיום",
    newBusiness: "עסק חדש",
    searchBusinessPlaceholder: "חיפוש לפי שם העסק...",
    search: "חיפוש",
    owner: "בעל העסק",
    statistics: "סטטיסטיקה",
    subscription: "מנוי",
    subscriptionStart: "תחילת מנוי",
    subscriptionEnd: "סיום מנוי",
    adminSubscriptionSub: "הצגת פרטי המנוי של העסק הנבחר",
    businessSubscriptionSub: "פרטי המנוי של העסק שלך במערכת",
    currentPlan: "החבילה הנוכחית",
    monthlyPlan: "חבילה חודשית",
    yearlyPlan: "חבילה שנתית",
    monthUnit: "חודש",
    yearUnit: "שנה",
    expired: "פג תוקף",
    remainingDays: "ימים שנותרו",
    subscriptionContactHint: "לחידוש המנוי או לשדרוג החבילה, יש ליצור קשר עם הנהלת המערכת.",
    noActiveSubscription: "אין מנוי פעיל",
    activateSubscriptionHint: "יש ליצור קשר עם הנהלת המערכת להפעלת המנוי של העסק.",
    control: "ניהול",
    renewSubscription: "חידוש מנוי",
    activate: "הפעלה",
    deactivate: "השבתה",
    monthly: "חודשי",
    yearly: "שנתי",
    appointmentsShort: "תורים",
    employeesShort: "עובדים",
    servicesShort: "שירותים",
    noBusinesses: "אין עסקים",
    addFirstBusinessForStart: "הוסיפו את העסק הראשון כדי להתחיל",
    bookingStepService: "שירות",
    bookingStepEmployee: "עובד",
    bookingStepDateTime: "יום ושעה",
    bookingStepDetails: "הפרטים שלך",
    bookingPageUnavailable: "לא ניתן לפתוח את עמוד ההזמנה",
    bookEasily: "הזמינו תור בקלות",
    chooseService: "בחרו שירות",
    chooseEmployee: "בחרו עובד",
    chooseDateTime: "בחרו יום ושעה",
    enterYourDetails: "הכניסו פרטים",
    freeService: "השירות בחינם",
    noServicesAvailable: "אין שירותים זמינים",
    anyAvailableEmployee: "כל עובד זמין",
    autoChooseEmployee: "נבחר את העובד הזמין הראשון בזמן המתאים",
    date: "תאריך",
    closedTodayTitle: "העסק סגור היום, עמכם הסליחה",
    nextOpenPrefix: "נשמח לקבל אתכם",
    nearestWorkingDay: "ביום העבודה הקרוב",
    allSlotsBooked: "כל התורים הזמינים תפוסים",
    tryAnotherDayOrEmployee: "נסו יום אחר או עובד אחר",
    continue: "המשך",
    fullName: "שם מלא",
    phoneNumber: "מספר טלפון",
    optionalEmail: "אימייל (אופציונלי)",
    freeServicePaymentHint: "השירות בחינם ואינו דורש תשלום",
    bookingUnavailableNoPayment: "מצטערים, לא ניתן להזמין כרגע כי לא הופעלה אף שיטת תשלום.",
    paymentMethod: "אמצעי תשלום",
    onlinePayment: "תשלום אונליין",
    payAtStore: "תשלום במקום",
    payOnlineHint: "שלמו עכשיו דרך השער",
    payAtStoreHint: "שלמו בעת ההגעה",
    confirmFreeBooking: "אישור תור בחינם",
    continueToPayment: "המשך לתשלום",
    poweredByBooking: "מופעל על ידי מערכת ניהול התורים",
    bookingRejectedTitle: "התור נדחה",
    bookingPendingTitle: "הבקשה ממתינה לאישור",
    bookingConfirmedTitle: "התור אושר",
    bookingRejectedText: "מצטערים, התור נדחה. ניתן לבחור מועד אחר.",
    bookingPendingText: "נעדכן כאן אם התור יאושר או יידחה.",
    bookingConfirmedText: "נשמח לראותכם. אלה פרטי התור:",
    bookAnother: "הזמנת תור נוסף",
    back: "חזרה",
    sunday: "ראשון",
    monday: "שני",
    tuesday: "שלישי",
    wednesday: "רביעי",
    thursday: "חמישי",
    friday: "שישי",
    saturday: "שבת",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    return LANGUAGES[saved] ? saved : "ar";
  });

  useEffect(() => {
    const meta = LANGUAGES[language] || LANGUAGES.ar;
    document.documentElement.lang = meta.code;
    document.documentElement.dir = meta.dir;
    document.body.dir = meta.dir;
    localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const value = useMemo(() => {
    const setLanguage = (next) => {
      if (LANGUAGES[next]) setLanguageState(next);
    };
    const t = (key) => dictionary[language]?.[key] || dictionary.ar[key] || key;
    return {
      language,
      lang: language,
      dir: LANGUAGES[language]?.dir || "rtl",
      setLanguage,
      t,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}
